local W, H = 960, 540
local floorY = 480

local function ground()
  return {x = 0, y = floorY, w = W, h = 60}
end

local function box(x, y)
  return {x = x, y = y or floorY - 28, w = 28, h = 28}
end

return {
  {
    name = "01 Wake",
    nameZh = "01 醒来",
    hint = "A/D or arrows move   Space/W/Up jump   Reach the exit",
    hintZh = "A/D 或方向键移动   空格/W/上 跳跃   抵达出口",
    start = {x = 54, y = floorY - 30},
    goal = {x = 880, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 260, y = 420, w = 120, h = 18}, {x = 510, y = 365, w = 120, h = 18}, {x = 720, y = 420, w = 120, h = 18}},
    boxes = {}, buttons = {}, doors = {}, lasers = {},
  },
  {
    name = "02 Door Signal",
    nameZh = "02 门的信号",
    hint = "Stand on the amber pad to open the blue door",
    hintZh = "站上琥珀色按钮，打开蓝色门",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground()}, boxes = {},
    buttons = {{id = "b1", x = 432, y = floorY - 10, w = 92, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 460, y = floorY - 86, w = 28, h = 86}},
    lasers = {},
  },
  {
    name = "03 First Shadow",
    nameZh = "03 第一个影子",
    hint = "Wait on the pad. Four seconds later your shadow repeats it.",
    hintZh = "在按钮上等待，4 秒后影子会重复你的动作",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 300, y = 430, w = 110, h = 16}}, boxes = {},
    buttons = {{id = "b1", x = 208, y = floorY - 10, w = 76, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 520, y = floorY - 94, w = 30, h = 94}},
    lasers = {},
  },
  {
    name = "04 Echo Route",
    nameZh = "04 回声路线",
    hint = "Make the past-self hold the left pad, then cross the opened route",
    hintZh = "让过去的自己踩住左侧按钮，然后穿过打开的路线",
    start = {x = 54, y = floorY - 30},
    goal = {x = 880, y = 336, w = 34, h = 64},
    solids = {ground(), {x = 560, y = 400, w = 130, h = 18}, {x = 760, y = 400, w = 160, h = 18}}, boxes = {},
    buttons = {{id = "b1", x = 180, y = floorY - 10, w = 76, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 700, y = 400, w = 30, h = 80}},
    lasers = {},
  },
  {
    name = "05 Light Block",
    nameZh = "05 挡住光束",
    hint = "Stand beside the beam, wait for your shadow, then cross while it dims",
    hintZh = "站在光束旁等影子出现，光束变暗时通过",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 430, y = 420, w = 72, h = 16}},
    boxes = {}, buttons = {}, doors = {},
    lasers = {{x = 500, y = 420, w = 18, h = 60}},
  },
  {
    name = "06 First Crate",
    nameZh = "06 第一个箱子",
    hint = "Push the crate onto the pad so the door stays open",
    hintZh = "把箱子推到按钮上，让门保持打开",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground()},
    boxes = {box(235)},
    buttons = {{id = "b1", x = 380, y = floorY - 10, w = 72, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 560, y = floorY - 92, w = 30, h = 92}},
    lasers = {},
  },
  {
    name = "07 Shadow Push",
    nameZh = "07 影子推箱",
    hint = "Record a push, then let the shadow move the crate onto the pad",
    hintZh = "先录下一次推箱，让影子把箱子推到按钮上",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 505, y = 430, w = 90, h = 16}},
    boxes = {box(260)},
    buttons = {{id = "b1", x = 432, y = floorY - 10, w = 76, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 620, y = floorY - 92, w = 30, h = 92}},
    lasers = {},
  },
  {
    name = "08 Split Duties",
    nameZh = "08 分工",
    hint = "Leave a crate for one door, then use your shadow for the next",
    hintZh = "用箱子守住第一扇门，再让影子处理第二扇门",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground()},
    boxes = {box(180)},
    buttons = {{id = "b1", x = 300, y = floorY - 10, w = 72, h = 10, target = "d1"}, {id = "b2", x = 520, y = floorY - 10, w = 72, h = 10, target = "d2"}},
    doors = {{id = "d1", x = 420, y = floorY - 92, w = 30, h = 92}, {id = "d2", x = 660, y = floorY - 92, w = 30, h = 92}},
    lasers = {},
  },
  {
    name = "09 Beam And Box",
    nameZh = "09 光束与箱子",
    hint = "Use the crate for the door, then let your shadow dim the beam",
    hintZh = "箱子负责开门，再让影子压暗光束",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 625, y = 420, w = 72, h = 16}},
    boxes = {box(230)},
    buttons = {{id = "b1", x = 380, y = floorY - 10, w = 72, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 515, y = floorY - 92, w = 30, h = 92}},
    lasers = {{x = 660, y = 420, w = 18, h = 60}},
  },
  {
    name = "10 High Echo",
    nameZh = "10 高处回声",
    hint = "Hold the lower pad with your shadow, then cross the long gate",
    hintZh = "让影子踩住下方按钮，然后穿过长门",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground()},
    boxes = {},
    buttons = {{id = "b1", x = 190, y = floorY - 10, w = 76, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 625, y = floorY - 92, w = 30, h = 92}},
    lasers = {},
  },
  {
    name = "11 Double Memory",
    nameZh = "11 双重记忆",
    hint = "Hold the pad for the door, then leave a second echo beside the beam",
    hintZh = "先守住按钮开门，再在光束旁留下第二段影子",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 620, y = 420, w = 72, h = 16}},
    boxes = {},
    buttons = {{id = "b1", x = 210, y = floorY - 10, w = 76, h = 10, target = "d1"}},
    doors = {{id = "d1", x = 430, y = floorY - 92, w = 30, h = 92}},
    lasers = {{x = 650, y = 420, w = 18, h = 60}},
  },
  {
    name = "Finale",
    nameZh = "终章",
    hint = "Crate for the first door, shadow for the second door, echo for the beam",
    hintZh = "箱子开第一扇门，影子开第二扇门，回声压暗光束",
    start = {x = 54, y = floorY - 30},
    goal = {x = 875, y = floorY - 64, w = 34, h = 64},
    solids = {ground(), {x = 710, y = 420, w = 72, h = 16}},
    boxes = {box(205)},
    buttons = {{id = "b1", x = 330, y = floorY - 10, w = 72, h = 10, target = "d1"}, {id = "b2", x = 545, y = floorY - 10, w = 72, h = 10, target = "d2"}},
    doors = {{id = "d1", x = 430, y = floorY - 92, w = 30, h = 92}, {id = "d2", x = 655, y = floorY - 92, w = 30, h = 92}},
    lasers = {{x = 740, y = 420, w = 18, h = 60}},
  },
}
